### ISSUE TITLE
Cant detect model with lidar

### ISSUE THREAD

**Issue by prat1kbhujbal** [robotics-upo/gazebo_sfm_plugin#1]
Hi, 
I am trying to visualize the model as an obstacle in rviz using the Lidar sensor but I can't see any collision, in other words, it ignores the collision of the model. Can you please help me with this?

**Comment by prat1kbhujbal** [comment]
Solved problem with lidar

**Comment by ai-winter** [comment]
Hello, @prat1kbhujbal 

I faced the same problem, could you please give me some suggestions?

**Comment by noeperez** [comment]
Hi,

You just need to change the type of your robot laser to gpu_ray.

**Comment by ai-winter** [comment]
@noeperez Thanks for your answer.

I have changed the laser to gpu version but it doesn't work.
```xml
  <gazebo reference="base_scan">
    <material>Gazebo/FlatBlack</material>
    <sensor type="gpu_ray" name="lds_lfcd_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>$(arg laser_visual)</visualize>

      <update_rate>5</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>0.0</min_angle>
            <max_angle>6.28319</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.120</min>
          <max>3.5</max>
          <resolution>0.015</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_lds_lfcd_controller" filename="libgazebo_ros_gpu_laser.so">
        <topicName>scan</topicName>
        <frameName>base_scan</frameName>
      </plugin>
    </sensor>
  </gazebo>
```

Is there anything wrong? Thanks for your help.

**Comment by prat1kbhujbal** [comment]
@ai-winter can't see any problem with the plugin, check if the laser works or if you can visualize scan data in Rviz for these changes with normal obstacles might be GPU not supported or a driver problem. Or else you can refer to this it works without GPU requirement- [https://github.com/JiangweiNEU/actor_collisions](https://github.com/JiangweiNEU/actor_collisions)

**Comment by noeperez** [comment]
Hi again,

as @prat1kbhujbal said. You need to be sure that Gazebo is using your GPU. The actor models do not have a collision model associated. So, they can be sensed using a graphical detection that can be done only by the GPU (gpu_ray).

**Comment by ai-winter** [comment]
Hello, @noeperez @prat1kbhujbal 
Thanks a lot for your help! The problem has been solved!

**Comment by brilianputraa** [comment]
@ai-winter Hi, could I ask you how you solved the problem? because I have the same problem as well, I changed the plugin type to GPU, but the laser scan in Rviz couldn't detect it

**Comment by ai-winter** [comment]
@brilianputraa 

Please refer to the project [ros_pedestrians_simulation](https://[github.com/ai-winter/ros_pedestrians_simulation](https://github.com/ai-winter/ros_pedestrians_simulation))
